  L.marker([-5662, 3401], {icon: cardIcon4}).addTo(map)
    .bindPopup("<h2>Gouvernement</h2><img class='logo' src='https://i.postimg.cc/FKFth8y8/image-1.png'><p><a href='https://i.postimg.cc/Xv1P4J7B/IMG-20230102-024358.jpg' data-lightbox='image-4' data-title='Gouvernement'>Ouvrir le visuel du lieu</a><h3>Siège du gouvernement</h3></p>");
  L.marker([-5744.6, 3472], {icon: cardIcon3}).addTo(map)
    .bindPopup("<h2>Hôpital</h2><img class='logo' src='https://i.postimg.cc/FsZRsgyd/image.png'><p><a href='https://i.postimg.cc/WpSLd9yv/neblife-fa8551fbc3a20dd3fd5c57cef430459e.png' data-lightbox='image-4' data-title='Hôpital'>Ouvrir le visuel du lieu</a><h3>Hôpital Mount Zonah</h3></p>");
  L.marker([-6558, 3981.2], {icon: cardIcon2}).addTo(map)
    .bindPopup("<h2>Commissairiat</h2><img class='logo' src='https://i.postimg.cc/jS9mbctb/image.png'><p><a href='https://i.postimg.cc/xC1DfqRc/IMG-20230102-033753.jpg' data-lightbox='image-4' data-title='Commissairiat'>Ouvrir le visuel du lieu</a><h3>Poste de police South Los Santos</h3></p>");
  L.marker([-6262, 3721.5], {icon: cardIcon1}).addTo(map)
    .bindPopup("<h2>Concessionnaire</h2><img class='logo' src='https://i.postimg.cc/L5VPRxP6/IMG-20221231-064139.png'><p><a href='https://i.postimg.cc/dtGMWqnR/concessionnairmap.jpg' data-lightbox='image-4' data-title='Concessionnaire'>Ouvrir le visuel du lieu</a><h3>Premium deluxe motorsport</h3></p>");
  L.marker([-5741.5, 4521.5], {icon: cardIcon5}).addTo(map)
    .bindPopup("<h2>LTD</h2><img class='logo' src='https://i.postimg.cc/NGHnvQhL/image.png'><p><a href='https://i.postimg.cc/c4GbsPZh/1856f919e8612-11f446-EF6-F3-CA740-BD3-71-FEE5-A69-D18-C63-A-message-428189191327662-1672614028623.jpg' data-lightbox='image-4' data-title='LTD'>Ouvrir le visuel du lieu</a><h3>LTD Mirror Park</h3></p>");
  L.marker([-6336.25, 2547.25], {icon: cardIcon8}).addTo(map)
    .bindPopup("<h2>Fête foraine</h2><img class='logo' src='https://i.postimg.cc/8PJDH4hh/image.png'><p><a href='https://i.postimg.cc/9MbX6fMZ/1.jpg' data-lightbox='image-4' data-title='Fête foraine'>Ouvrir le visuel du lieu</a><h3>Fête foraine Del Perro</h3></p>");
  L.marker([-6232.6, 4240], {icon: cardIcon6}).addTo(map)
    .bindPopup("<h2>Los Santos Custom</h2><img class='logo' src='https://i.postimg.cc/250TR87b/image.png'><p><a href='https://i.postimg.cc/L8Cc8mJX/18570451fc09-11f446-EF6-F3-CA740-BD3-71-FEE5-A69-D18-C63-A-message-428192208281975-1672625813601.jpg' data-lightbox='image-4' data-title='Los Santos Custom'>Ouvrir le visuel du lieu</a><h3>LS Custom Mesa</h3></p>");
  L.marker([-7339, 3075.5], {icon: cardIcon7}).addTo(map)
    .bindPopup("<h2>Aéroport Los Santos</h2><img class='logo' src='https://i.postimg.cc/Mph3X4Jd/image.png'><p><a href='https://i.postimg.cc/8cPtqgLP/LSIA-Birds-eye-view.jpg' data-lightbox='image-4' data-title='Aéroport'>Ouvrir le visuel du lieu</a><h3>Aéroport Los Santos</h3></p>");
  L.marker([-7501.5, 4324], {icon: cardIcon10}).addTo(map)
    .bindPopup("<h2>Port commercial LS</h2><img class='logo' src='https://i.postimg.cc/cL04PsHN/image.png'><p><a href='https://i.postimg.cc/3J2BrZZH/Jetsam-Terminal-GTAV.png' data-lightbox='image-4' data-title='Port commercial'>Ouvrir le visuel du lieu</a><h3>Port commercial Los Santos</h3></p>");
  L.marker([-1867.5, 4066], {icon: cardIcon9}).addTo(map)
    .bindPopup("<h2>Mont Chilliad</h2><img class='logo' src='https://i.postimg.cc/NfPgM1Gp/image.png'><p><a href='https://i.postimg.cc/QxZQzTZY/Mount-Chiliad-GTAV.webp' data-lightbox='image-4' data-title='Mont Chilliad'>Ouvrir le visuel du lieu</a><h3>Mont Chilliad</h3></p>");
  L.marker([-3815.5, 4963.5], {icon: cardIcon11}).addTo(map)
    .bindPopup("<h2>Pénitenier Bolingbroke</h2><img class='logo' src='https://i.postimg.cc/Rhj0cTT1/image.png'><p><a href='https://i.postimg.cc/5083LP11/Bolingbroke-Penitentiary-GTAV.png' data-lightbox='image-4' data-title='Pénitencierhaute sécurité'>Ouvrir le visuel du lieu</a><h3>Pénitencier Bolingbroke</h3></p>");
  L.marker([-2773, 3386.5], {icon: cardIcon12}).addTo(map)
    .bindPopup("<h2>Raton Canyon (Lookout Post)</h2><p><a href='https://content.rockstarnews.ru/up/images/95500c59962e3784ac0ebe79cfee0e9c.jpg' data-lightbox='image-11' data-title='Raton Canyon (Lookout Post)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-3088.25, 3809.5], {icon: cardIcon13}).addTo(map)
    .bindPopup("<h2>Stab City (Lost Hangout)</h2><p><a href='https://content.rockstarnews.ru/up/images/d370acd7a95f61953c65ab7c5f88e1bc.jpg' data-lightbox='image-11' data-title='Stab City (Lost Hangout)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-3176, 4351], {icon: cardIcon14}).addTo(map)
    .bindPopup("<h2>Grand Senora Desert (On the side of a road)</h2><p><a href='https://content.rockstarnews.ru/up/images/7e9ba3967c403c7b2a4fbcdcaf5f20da.jpg' data-lightbox='image-11' data-title='Grand Senora Desert (On the side of a road)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-3165.75, 4873], {icon: cardIcon15}).addTo(map)
    .bindPopup("<h2>Sandy Shores Fire Station</h2><p><a href='https://content.rockstarnews.ru/up/images/432f08f0adae6a04e1b27a267726872b.jpg' data-lightbox='image-11' data-title='Sandy Shores Fire Station'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-3249.5, 5568.5], {icon: cardIcon16}).addTo(map)
    .bindPopup("<h2>Senora Freeway (YouTool hardware store)</h2><p><a href='https://content.rockstarnews.ru/up/images/f03d8317660986ab01b4cfc59e03f872.png' data-lightbox='image-11' data-title='Senora Freeway (YouTool hardware store)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-3524.5, 5071.5], {icon: cardIcon17}).addTo(map)
    .bindPopup("<h2>Yellow Jack Bar</h2><p><a href='https://content.rockstarnews.ru/up/images/4cefa6c429608d139827d9671b1a3cfc.jpg' data-lightbox='image-11' data-title='Yellow Jack Bar'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-3839, 5299.5], {icon: cardIcon18}).addTo(map)
    .bindPopup("<h2>Grand Senora Desert Trailer Park</h2><p><a href='https://content.rockstarnews.ru/up/images/c321c16b535ba788525acdc91770f705.jpg' data-lightbox='image-11' data-title='Grand Senora Desert Trailer Park'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-3871.25, 4240.5], {icon: cardIcon19}).addTo(map)
    .bindPopup("<h2>Grand Senora Desert (Rebel Radio station)</h2><p><a href='https://content.rockstarnews.ru/up/images/6f9d9a486e004a27d7120efa2a4202e3.png' data-lightbox='image-11' data-title='Grand Senora Desert (Rebel Radio station)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-3500, 3879.5], {icon: cardIcon20}).addTo(map)
    .bindPopup("<h2>Grand Senora Desert (Near house by Industrial Plant)</h2><p><a href='https://content.rockstarnews.ru/up/images/9fcfe06ba99dfc79fb60b7fe9832299d.png' data-lightbox='image-11' data-title='Grand Senora Desert (Near house by Industrial Plant)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-3862, 3575], {icon: cardIcon21}).addTo(map)
    .bindPopup("<h2>Great Chaparral (House south of the Route 68 Church)</h2><p><a href='https://content.rockstarnews.ru/up/images/c6bdd775892ac79bcc9ce1538214d34b.png' data-lightbox='image-11' data-title='Great Chaparral (House south of the Route 68 Church)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-3744, 3032], {icon: cardIcon22}).addTo(map)
    .bindPopup("<h2>Zancudo (Discount Store)</h2><p><a href='https://content.rockstarnews.ru/up/images/d5d9c83e1d64ca67ee5f4ec05dbeb138.jpg' data-lightbox='image-11' data-title='Zancudo (Discount Store)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-3298.5, 2241.75], {icon: cardIcon23}).addTo(map)
    .bindPopup("<h2>Zancudo (Zancudo Millitary Base)</h2><p><a href='https://content.rockstarnews.ru/up/images/d544693b1a5c508a295af5a263d4b5c3.jpg' data-lightbox='image-11' data-title='Zancudo (Zancudo Millitary Base)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-4799.5, 1680], {icon: cardIcon24}).addTo(map)
    .bindPopup("<h2>Chumash (Nelson's General Store)</h2><p><a href='https://content.rockstarnews.ru/up/images/b27cc83a95325231390fff74eb8b32b5.png' data-lightbox='image-11' data-title='Chumash (Nelson's General Store)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5143, 1750], {icon: cardIcon25}).addTo(map)
    .bindPopup("<h2>Banham Canyon (In the 2nd Convenience Store)</h2><p><a href='https://content.rockstarnews.ru/up/images/a4076ea008b266bc2151962ffbab7dd3.png' data-lightbox='image-11' data-title='Banham Canyon (In the 2nd Convenience Store)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5004.5, 2570], {icon: cardIcon26}).addTo(map)
    .bindPopup("<h2>Richmen Glen (Convenience Store)</h2><p><a href='https://content.rockstarnews.ru/up/images/e98d5cc21a30d2aa25da2939c89dfb1e.jpg' data-lightbox='image-11' data-title='Richmen Glen (Convenience Store)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-4730, 3476.5], {icon: cardIcon27}).addTo(map)
    .bindPopup("<h2>Vinewood Hills (Observatory)</h2><p><a href='https://content.rockstarnews.ru/up/images/103a7e20345e35b058ececbc55a1dd03.png' data-lightbox='image-11' data-title='Vinewood Hills (Observatory)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-4783.75, 4737.5], {icon: cardIcon28}).addTo(map)
    .bindPopup("<h2>Vinewood Hills (Madrazo's Ranch)</h2><p><a href='https://content.rockstarnews.ru/up/images/05217a8f50e6305d692cff973d9fbb93.jpg' data-lightbox='image-11' data-title='Vinewood Hills (Madrazo's Ranch)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5338.5, 5450.5], {icon: cardIcon29}).addTo(map)
    .bindPopup("<h2>Tataviam Mt. (Ammu-Nation)</h2><p><a href='https://content.rockstarnews.ru/up/images/9a2c2e64da4cf6482a49145eede25318.jpg' data-lightbox='image-11' data-title='Tataviam Mt. (Ammu-Nation)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5158, 3484], {icon: cardIcon30}).addTo(map)
    .bindPopup("<h2>Vinewood Hills (Behind a yellow house in Vinewood Hills on Didion Drive)</h2><p><a href='https://content.rockstarnews.ru/up/images/0ace054e882228ee8349ba375b70cdd8.png' data-lightbox='image-11' data-title='Vinewood Hills (Behind a yellow house in Vinewood Hills on Didion Drive)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5296, 3690], {icon: cardIcon31}).addTo(map)
    .bindPopup("<h2>West Vinewood (Gentry Manor Hotel)</h2><p><a href='https://content.rockstarnews.ru/up/images/196e37802dac2ed407dd598313b07ddb.jpg' data-lightbox='image-11' data-title='West Vinewood (Gentry Manor Hotel)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5389, 3914.5], {icon: cardIcon32}).addTo(map)
    .bindPopup("<h2>Pacific Standard Bank</h2><p><a href='https://content.rockstarnews.ru/up/images/765975dfe817ad4a426f77d18f979f38.jpg' data-lightbox='image-11' data-title='Pacific Standard Bank'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5650.75, 4114], {icon: cardIcon33}).addTo(map)
    .bindPopup("<h2>Hawick (Auto Exotic garage)</h2><p><a href='https://content.rockstarnews.ru/up/images/d183e455541e489e5f34368e29dd846b.jpg' data-lightbox='image-11' data-title='Hawick (Auto Exotic garage)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-1310.5, 4978.75], {icon: cardIcon34}).addTo(map)
    .bindPopup("<h2>Mirror Park (Convenience Store)</h2><p><a href='https://content.rockstarnews.ru/up/images/f4ad0cd8db86e59853b96b723e66b131.jpg' data-lightbox='image-11' data-title='Mirror Park (Convenience Store)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5724, 3654.5], {icon: cardIcon35}).addTo(map)
    .bindPopup("<h2>Ponsonbys (Burton)</h2><p><a href='https://content.rockstarnews.ru/up/images/96b1c5a0ebff3bf18e6b6ac1d2696169.jpg' data-lightbox='image-11' data-title='Ponsonbys (Burton)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5463, 3119.5], {icon: cardIcon36}).addTo(map)
    .bindPopup("<h2>Rockford Hills (Mansion at the end of Steele Way)</h2><p><a href='https://content.rockstarnews.ru/up/images/aec2fcd7e487d35cbe5c5d15ebc82682.jpg' data-lightbox='image-11' data-title='Rockford Hills (Mansion at the end of Steele Way)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5682.5, 2991], {icon: cardIcon37}).addTo(map)
    .bindPopup("<h2>Rockford Hills (Building across from Life Invader)</h2><p><a href='https://content.rockstarnews.ru/up/images/bda0aefd7d9624ebf4d88dce6eae5f30.jpg' data-lightbox='image-11' data-title='Rockford Hills (Building across from Life Invader)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5601, 2760.5], {icon: cardIcon38}).addTo(map)
    .bindPopup("<h2>Richman (Backyard of mansion at intersection of West Eclipse and Tongva Drive)</h2><p><a href='https://content.rockstarnews.ru/up/images/b1e4025b64ec61a86f00938b805e4aec.png' data-lightbox='image-11' data-title='Richman (Backyard of mansion at intersection of West Eclipse and Tongva Drive)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5875, 3008], {icon: cardIcon39}).addTo(map)
    .bindPopup("<h2>Richards Majestic (Movie Studio)</h2><p><a href='https://content.rockstarnews.ru/up/images/68c7b2432530c612d8bd121a4c2e26af.png' data-lightbox='image-11' data-title='Richards Majestic (Movie Studio)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-2030.5, 5687], {icon: cardIcon40}).addTo(map)
    .bindPopup("<h2>Del Perro Beach (End of the pier)</h2><p><a href='https://content.rockstarnews.ru/up/images/4e2d58a8a39458014d4647e519887eaf.png' data-lightbox='image-11' data-title='Del Perro Beach (End of the pier)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-6271, 2911.5], {icon: cardIcon41}).addTo(map)
    .bindPopup("<h2>Vespucci Canals (Barber Shop)</h2><p><a href='https://content.rockstarnews.ru/up/images/c67cb451c21becfcf7c57e33d8562090.jpg' data-lightbox='image-11' data-title='Vespucci Canals (Barber Shop)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-6557.5, 2962.5], {icon: cardIcon42}).addTo(map)
    .bindPopup("<h2>Vespucci Beach (Musclehead Gym)</h2><p><a href='https://content.rockstarnews.ru/up/images/c643ea35c09162d9635278c45e3fb67b.png' data-lightbox='image-11' data-title='Vespucci Beach (Musclehead Gym)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-6377, 3401], {icon: cardIcon43}).addTo(map)
    .bindPopup("<h2>Little Seoul (Tram station near Heli Tours)</h2><p><a href='https://content.rockstarnews.ru/up/images/d3b7a8f62abe58fabd61a19cd87dab97.jpg' data-lightbox='image-11' data-title='Little Seoul (Tram station near Heli Tours)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-6263, 3768.5], {icon: cardIcon44}).addTo(map)
    .bindPopup("<h2>Ammu-nation with shooting range (Pillbox Hill)</h2><p><a href='https://content.rockstarnews.ru/up/images/5fdc4701721cc68dcf1fe9f25b022e5f.jpg' data-lightbox='image-11' data-title='Ammu-nation with shooting range (Pillbox Hill)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-6381.25, 3834.75], {icon: cardIcon45}).addTo(map)
    .bindPopup("<h2>Vanilla Unicorn</h2><p><a href='https://content.rockstarnews.ru/up/images/0442e218eefdd63864a816b914930d24.jpg' data-lightbox='image-11' data-title='Vanilla Unicorn'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-6613, 3897.5], {icon: cardIcon46}).addTo(map)
    .bindPopup("<h2>Davis Fire Department on Macdonald Street</h2><p><a href='https://content.rockstarnews.ru/up/images/d42aba2c28b4cb1fd4c5f7e4002b70de.png' data-lightbox='image-11' data-title='Davis Fire Department on Macdonald Street'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-6856, 3719], {icon: cardIcon47}).addTo(map)
    .bindPopup("<h2>Davis (Maze Bank Arena parking lot)</h2><p><a href='https://content.rockstarnews.ru/up/images/ed64f6446b9a8a4fde7932b1d54585fa.jpg' data-lightbox='image-11' data-title='Davis (Maze Bank Arena parking lot)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-2384.5, 5159], {icon: cardIcon48}).addTo(map)
    .bindPopup("<h2>LS Intl. Airport (First floor front entrance of LSIA)</h2><p><a href='https://content.rockstarnews.ru/up/images/d885f0751ccef4a4d3015f362427cb9a.jpg' data-lightbox='image-11' data-title='LS Intl. Airport (First floor front entrance of LSIA)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-6178, 4507], {icon: cardIcon53}).addTo(map)
    .bindPopup("<h2>Rob’s Liquor (Murrieta Heights)</h2><p><a href='https://content.rockstarnews.ru/up/images/755bbec3f4e58f30d7f1de57da5c4004.jpg' data-lightbox='image-11' data-title='Robs Liquor (Murrieta Heights)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-6619.5, 4632.5], {icon: cardIcon52}).addTo(map)
    .bindPopup("<h2>El Burro Heights (Tattoo Parlor)</h2><p><a href='https://content.rockstarnews.ru/up/images/0bb0aad07706d7bada4f881d9a3b387e.jpg' data-lightbox='image-11' data-title='El Burro Heights (Tattoo Parlor)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-6717, 4404.5], {icon: cardIcon51}).addTo(map)
    .bindPopup("<h2>La Mesa (Behind cheap vehicle warehouse)</h2><p><a href='https://content.rockstarnews.ru/up/images/57bb237c11b556f1d09b5fe48aef2e09.png' data-lightbox='image-11' data-title='La Mesa (Behind cheap vehicle warehouse)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-6946, 4298], {icon: cardIcon50}).addTo(map)
    .bindPopup("<h2>Ammu-nation with shooting range (Cypress Flats)</h2><p><a href='https://content.rockstarnews.ru/up/images/1088c4e0602025b1b1fed1b8f51b0fcb.jpg' data-lightbox='image-11' data-title='Ammu-nation with shooting range (Cypress Flats)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-2688, 5536.5], {icon: cardIcon49}).addTo(map)
    .bindPopup("<h2>Terminal (Jetsam Terminal Building)</h2><p><a href='https://content.rockstarnews.ru/up/images/51b8ea8b3ee82b853d6c23394f2a69ed.jpg' data-lightbox='image-11' data-title='Terminal (Jetsam Terminal Building)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
  L.marker([-5963, 3888], {icon: cardIcon54}).addTo(map)
    .bindPopup("<h2>Pillbox Hill (Between FBI & IAA)</h2><p><a href='https://content.rockstarnews.ru/up/images/c23af6414f51829305492271523aff12.jpg' data-lightbox='image-11' data-title='Pillbox Hill (Between FBI & IAA)'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-1140.750/3857.500'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div>");
